version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/app
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
  AfterInstall:
    - location: scripts/install_dependencies.sh
  ApplicationStart:
    - location: scripts/start_server.sh
